@startuml
'https://plantuml.com/state-diagram

state Run
State Win
State Draw

[*] -> Run


state Play <<choice>>
Run --> Play: play()
Play -> Draw : [draw]
Play -left-> Win : [winner]
Play -up-> Run : [else]

Win -up-> Run: new()
Draw -up-> Run: new()
Run -up-> Win: new()

@enduml